"use server";

import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";


export async function getBookings(start: Date, end: Date) {
  try {
    const bookings = await prisma.booking.findMany({
      where: {
        startTime: {
          gte: start,
        },
        endTime: {
          lte: end,
        },
      },
      select: {
        id: true,
        startTime: true,
        endTime: true,
        user: true,
      },
    });
    return bookings;
  } catch (error) {
    console.error("Failed to fetch bookings:", error);
    return [];
  }
}


export async function createBooking(prevState: any, formData: FormData) {
  const user = formData.get("user") as string;
  const startTime = formData.get("startTime") as string; // ISO string
  const endTime = formData.get("endTime") as string;     // ISO string
  const deviceToken = formData.get("deviceToken") as string | null;

  if (!user || !startTime || !endTime) {
    return { message: "Missing required fields", success: false };
  }

  const start = new Date(startTime);
  const end = new Date(endTime);
  const now = new Date();

  try {
    // Transaction to ensure no double booking
    const booking = await prisma.$transaction(async (tx) => {
      // 1. Enforce Rate Limiting (Quota)
      if (deviceToken) {
        const activeBookingsCount = await tx.booking.count({
          where: {
            deviceToken: deviceToken,
            endTime: { gt: now },
          },
        });

        if (activeBookingsCount >= 3) {
          throw new Error("You have reached the limit of 3 active bookings. Please delete an older booking or wait until one finishes.");
        }
      }

      // 2. Check for overlap
      const existing = await tx.booking.findFirst({
        where: {
          OR: [
            {
              startTime: { lt: end },
              endTime: { gt: start },
            },
          ],
        },
      });

      if (existing) {
        throw new Error("Time slot already booked!");
      }

      return await tx.booking.create({
        data: {
          user,
          startTime: start,
          endTime: end,
          deviceToken: deviceToken || undefined,
          // deleteToken is auto-generated by @default(uuid()) in schema
        },
      });
    }, {
      isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
    });

    revalidatePath("/book");
    revalidatePath("/");
    
    // Use type assertion to avoid build errors if types aren't fully synced yet
    const newBooking = booking as any;
    
    return { 
      message: "Booking success!", 
      success: true, 
      bookingId: newBooking.id,
      deleteToken: newBooking.deleteToken 
    };
  } catch (error: any) {
    console.error("Booking creation failed:", error);
    console.error("Error details:", {
      message: error.message,
      code: error.code,
      meta: error.meta,
      stack: error.stack
    });

    if (error.message === "Time slot already booked!") {
        return { message: "Time slot already booked!", success: false };
    }
    // Handle serialization failure (code 40001 in pg)
    if (error.code === 'P2034') { 
         return { message: "Booking conflict (db), please try again.", success: false };
    }
    return { message: "Failed to create booking: " + (error.message || "Unknown error"), success: false };
  }
}

export async function deleteBooking(bookingId: string, deleteToken: string) {
  try {
    // First verify the token matches
    const booking = await prisma.booking.findUnique({
      where: { id: bookingId },
      select: { deleteToken: true },
    });

    if (!booking) {
      return { success: false, message: "Booking not found" };
    }

    if (booking.deleteToken !== deleteToken) {
      return { success: false, message: "Unauthorized - you can only delete your own bookings" };
    }

    // Token matches, proceed with deletion
    await prisma.booking.delete({
      where: { id: bookingId },
    });
    
    revalidatePath("/book");
    revalidatePath("/");
    return { success: true };
  } catch (error) {
    console.error("Failed to delete booking:", error);
    return { success: false, message: "Failed to delete" };
  }
}
