"use server";

import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";


export async function getBookings(start: Date, end: Date) {
  try {
    const bookings = await prisma.booking.findMany({
      where: {
        startTime: {
          gte: start,
        },
        endTime: {
          lte: end,
        },
      },
      select: {
        id: true,
        startTime: true,
        endTime: true,
        user: true,
      },
    });
    return bookings;
  } catch (error) {
    console.error("Failed to fetch bookings:", error);
    return [];
  }
}


import { cookies } from "next/headers";
import { z } from "zod";

const bookingSchema = z.object({
  user: z.string().min(2, "Name must be at least 2 characters").max(50, "Name must be less than 50 characters").regex(/^[a-zA-Z0-9\s\-_]+$/, "Name contains invalid characters"),
  startTime: z.string().datetime(),
  endTime: z.string().datetime(),
});

export async function createBooking(prevState: any, formData: FormData) {
  const rawData = {
    user: formData.get("user"),
    startTime: formData.get("startTime"),
    endTime: formData.get("endTime"),
  };

  // 1. Zod Validation
  const validatedFields = bookingSchema.safeParse(rawData);

  if (!validatedFields.success) {
    const firstError = validatedFields.error.issues?.[0]?.message || "Invalid input";
    return {
      success: false,
      message: firstError,
    };
  }

  const { user, startTime, endTime } = validatedFields.data;
  
  // 2. Secure Rate Limiting via Cookie
  const cookieStore = await cookies();
  const deviceToken = cookieStore.get("device_session")?.value;

  // STRICT SECURITY: Require session cookie to prevent rate limit bypass
  if (!deviceToken) {
     return { success: false, message: "Session invalid. Please refresh the page or enable cookies." };
  }

  const start = new Date(startTime);
  const end = new Date(endTime);
  const now = new Date();

  // DEBUG LOGGING
  console.log(`[CreateBooking] Attempt by ${user}`);
  console.log(`[CreateBooking] Start: ${start.toISOString()} (Local: ${start.toLocaleString()})`);
  console.log(`[CreateBooking] End:   ${end.toISOString()} (Local: ${end.toLocaleString()})`);
  
  // VALIDATION:
  // 0. Date Validity Check
  if (isNaN(start.getTime()) || isNaN(end.getTime())) {
      return { message: "Invalid date format.", success: false };
  }

  // 1. End must be after Start
  if (end <= start) {
      return { message: "End time must be after start time.", success: false };
  }

  // 1b. Max duration 8 hours
  const durationHours = (end.getTime() - start.getTime()) / (1000 * 60 * 60);
  console.log(`[CreateBooking] Duration: ${durationHours} hours`);

  if (durationHours > 8) {
    console.log(`[CreateBooking] BLOCKED: Duration > 8`);
    return { message: "Booking cannot exceed 8 hours.", success: false };
  }

  // 2. Kitchen hours 6 AM - 10 PM
  const startHour = start.getHours();
  const endHour = end.getHours();
  // Check if starts before 6 AM
  if (startHour < 6) {
      return { message: "Kitchen opens at 6 AM.", success: false };
  }
  // Check if ends after 10 PM (22:00)
  // If endHour is > 22, OR if endHour is 22 AND minutes > 0
  if (endHour > 22 || (endHour === 22 && end.getMinutes() > 0)) {
      return { message: "Kitchen closes at 10 PM.", success: false };
  }
  
  // 3. Must be same day (implicit in 10 PM check if duration is short, but good to be explicit for safety)
  if (start.getDate() !== end.getDate() || start.getMonth() !== end.getMonth()) {
      return { message: "Bookings must be within a single day.", success: false };
  }

  try {
    // Transaction to ensure no double booking
    const booking = await prisma.$transaction(async (tx) => {
      // 1. Enforce Rate Limiting (Quota)
      if (deviceToken) {
        const activeBookingsCount = await tx.booking.count({
          where: {
            deviceToken: deviceToken,
            endTime: { gt: now },
          },
        });

        if (activeBookingsCount >= 3) {
          throw new Error("You have reached the limit of 3 active bookings. Please delete an older booking or wait until one finishes.");
        }
      }

      // 2. Check for overlap
      const existing = await tx.booking.findFirst({
        where: {
          OR: [
            {
              startTime: { lt: end },
              endTime: { gt: start },
            },
          ],
        },
      });

      if (existing) {
        throw new Error("Time slot already booked!");
      }

      return await tx.booking.create({
        data: {
          user, // Sanitized/validated by Zod
          startTime: start,
          endTime: end,
          deviceToken: deviceToken || undefined, // Use cookie value
          // deleteToken is auto-generated by @default(uuid()) in schema
        },
      });
    }, {
      isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
    });

    revalidatePath("/book");
    revalidatePath("/");
    
    // Use type assertion to avoid build errors if types aren't fully synced yet
    const newBooking = booking as any;
    
    return { 
      message: "Booking success!", 
      success: true, 
      bookingId: newBooking.id,
      deleteToken: newBooking.deleteToken 
    };
  } catch (error: any) {
    console.error("Booking creation failed:", error);
    // ... validation error handling
    if (error.message === "Time slot already booked!") {
        return { message: "Time slot already booked!", success: false };
    }
    // Handle serialization failure (code 40001 in pg)
    if (error.code === 'P2034') { 
         return { message: "Booking conflict (db), please try again.", success: false };
    }
    return { message: "Failed to create booking: " + (error.message || "Unknown error"), success: false };
  }
}

export async function deleteBooking(bookingId: string, deleteToken: string) {
  try {
    // First verify the token matches
    const booking = await prisma.booking.findUnique({
      where: { id: bookingId },
      select: { deleteToken: true },
    });

    if (!booking) {
      return { success: false, message: "Booking not found" };
    }

    if (booking.deleteToken !== deleteToken) {
      return { success: false, message: "Unauthorized - you can only delete your own bookings" };
    }

    // Token matches, proceed with deletion
    await prisma.booking.delete({
      where: { id: bookingId },
    });
    
    revalidatePath("/book");
    revalidatePath("/");
    return { success: true };
  } catch (error) {
    console.error("Failed to delete booking:", error);
    return { success: false, message: "Failed to delete" };
  }
}
